version: '3'

networks:
  clbb:
    external: true

services:
  api_gateway:
    container_name: api_gateway
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8520
    ports:
      - "8520:8520"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - clbb
